services:
  - type: web
    name: bezaleelcourt-1
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn property.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: SUPABASE_URL
        value: https://kwoimnikoqaiaollnuny.supabase.co
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@gmail.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: bezaleelcourt12345@
