services:
  - type: web
    name: bezaleelcourt-1
    env: python
    region: oregon
    buildCommand: echo "Starting Workflow................."
    startCommand: ./build_files.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: SUPABASE_URL
        value: https://kwoimnikoqaiaollnuny.supabase.co
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@gmail.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: bezaleelcourt12345@
